config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/2.0.0
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/interTwin-eu/interLink:
      branch: main
      repo: https://github.com/interTwin-eu/interLink
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/interTwin-eu/interLink git:
        commands:
        - /usr/bin/env sh .sqa/script.tacky-orchid-warthog.sh
        container: qc.acc_sleepy-charcoal-squid
  QC.Doc:
    repos:
      github.com/interTwin-eu/interLink find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.tacky-platinum-crocodile.sh
        container: qc.doc_chummy-corn-hippopotamus
      github.com/interTwin-eu/interLink git:
        commands:
        - /usr/bin/env sh .sqa/script.scanty-cerise-salamander.sh
        container: qc.doc_bluesy-teal-saola
  QC.Lic:
    repos:
      github.com/interTwin-eu/interLink licensee:
        commands:
        - /usr/bin/env sh .sqa/script.boozy-orange-hornet.sh
        container: qc.lic_scummy-cinnabar-stoat
  QC.Ver:
    repos:
      github.com/interTwin-eu/interLink get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.wimpy-olivine-bonobo.sh
        container: qc.ver_queasy-lilac-oyster
timeout: 5400
